### ISSUE TITLE
Tolerance disables prefix search

### ISSUE THREAD

**Issue by flodiebold** [oramasearch/orama#544]
### Describe the bug

Usually e.g. `Chris` matches `Christopher`, but setting `tolerance` to 1 makes it not match anymore. I'm not sure whether this is intentional, but it's at least surprising.

### To Reproduce

```ts
      const db = await create({
        schema: {
          name: 'string',
        } as const,
        components: {
          tokenizer: {
            stemming: true,
            stopWords: englishStopwords,
          },
        },
      })

      await insert(db, { name: "Christopher" })
      const result = await search(db, { term: 'Chris', tolerance: 1 })
      // result should contain the document, but does not
```

### Expected behavior

Ideally I'd like to be able to search with tolerance _and_ allow matching prefixes.

### Environment Info

```bash
Orama 2.0.0-beta.4
```

### Affected areas

Search

### Additional context

If it's not intentional, I could look into fixing this.

**Comment by rishi-raj-jain** [comment]
Can I be assigned this?

/attempt 544

**Comment by b4s36t4** [comment]
@micheleriva I don't think this is a bug.

> The Levenshtein distance is a string metric for measuring the difference between two sequences. Informally, the Levenshtein distance between two words is the minimum number of single-character edits (insertions, deletions or substitutions) required to change one word into the other.

Documentation for `tolerance` property from docs.oramasearch.com, if we consider words `Chris` and `Christopher` the distance between these two words is around 6, considering we count from (0) or some other way, having tolerance `1` wouldn't result the inserted document. 

I tried in local, setting tolerance as `6` works as expected, maybe this is expected. One should carefully decide about value for tolerance before doing search.


<img width="867" alt="Screenshot 2023-12-02 at 12 11 34 AM" src="https://github.com/oramasearch/orama/assets/59088937/f9e78aaa-8736-40eb-a33c-5064dc36dff4">

cc: @flodiebold

**Comment by rishi-raj-jain** [comment]
@b4s36t4  Christo should match right?

**Comment by b4s36t4** [comment]
If we have tolerance as `4` it should (maybe 3 also works not sure why :))

**Comment by rishi-raj-jain** [comment]
Oh I see yeah, the `difference <= originalTolerance` with the bounded check allows us to enforce this.

**Comment by rishi-raj-jain** [comment]
https://docs.oramasearch.com/open-source/usage/search/introduction#typo-tolerance

**Comment by b4s36t4** [comment]
Yep, that's it.

**Comment by rishi-raj-jain** [comment]
I wonder how, `Christop` with tolerance works tho.

**Comment by rishi-raj-jain** [comment]
<img width="1061" alt="Screenshot 2023-12-02 at 12 24 31 AM" src="https://github.com/oramasearch/orama/assets/46300090/e71ec3b5-b4d5-41ba-9e5a-4c72d8c15373">

the distance for them is 3

**Comment by flodiebold** [comment]
Yes, `Chris` doesn't match `Christopher` if you purely consider Levenshtein distance. It does match as a pure prefix though, and it's at least surprising that increasing `tolerance` from 0 to 1 completely disables prefix matches like this.

**Comment by rishi-raj-jain** [comment]
> Then there's something happening in between, maybe word matching etc happening.

investigating..

**Comment by rishi-raj-jain** [comment]
ah so when stemming is enabled by stemming: true

**Comment by rishi-raj-jain** [comment]
orama computes the token as `christoph` instead of `christopher`

<img width="393" alt="Screenshot 2023-12-02 at 2 07 20 AM" src="https://github.com/oramasearch/orama/assets/46300090/f63b410f-8715-4d7c-a7ff-5db8cc0ca9a0">

**Comment by rishi-raj-jain** [comment]
and hence it is able to match `Christop` with tolerance 1, only because stemming is enabled.

**Comment by micheleriva** [comment]
@rishi-raj-jain I confirm that, thanks for your efforts and analysis

**Comment by jkcs** [comment]
@micheleriva I came up with an idea. Can we add a property to allow both the findLevenshtein method and the default find to execute?

**Comment by SP321** [comment]
@micheleriva Is the feature supposed to match
1. all tokens with exact prefix + all tokens within Levenshtein tolerance.
Example.
`db="aaaa","abaaa","acaaa"`
`search aa with tolerance 1 matches only "aaaa",`

or

2. all tokens having a prefix within Levenshtein tolerance.
Example.
`db="aaaa","abaaa","acaaa"`
`search "aa" with tolerance 1 matches all strings. as all prefixes("aa","ab" and "ac") are within tolerance 1`

**Comment by micheleriva** [comment]
Fixed with #580

**Comment by SP321** [comment]
> Fixed with #580

This doesn't completely fix the issue. Radix tree is not traversed for entire prefix.

**Comment by rishi-raj-jain** [comment]
@micheleriva 

How's the awarded fix any different from mine?

https://github.com/oramasearch/orama/pull/560/files#diff-0a81a5033e2159840deb1d340175b3174049271f7744023924a53dc3e5087865R226

I've also added a flag that helps disable prefix search as we se agreed on https://github.com/oramasearch/orama/pull/560/#issuecomment-1837185755

**Comment by rishabmahesh** [comment]
This is the code I tried: -

```
const db = await orama.create({
    schema: {
        name: 'string',
    },
    components: {
        tokenizer: {
            stemming: true,
            stopWords: englishStopwords,
        },
    },
})

await orama.insert(db, { name: "a game" })
await orama.insert(db, { name: "apple is a" })
await orama.insert(db, { name: "to serve as a" })
await orama.insert(db, { name: "effort. apple is a" })
await orama.insert(db, { name: "(Optional) Define assertions with the SDK" })
await orama.insert(db, { name: "of poisonous spike-pits, nay, a" })
await orama.insert(db, { name: "you can always assert that it is incorrect" })

const result = await orama.search(db, {
    term: 'asser', tolerance: 1
})
console.log(result.hits)
```

This was the output I got: -
```
[
  {
    id: '78890398-5',
    score: 0.971091301243235,
    document: { name: '(Optional) Define assertions with the SDK' }
  },
  {
    id: '78890398-1',
    score: 0.8999873298772428,
    document: { name: 'a game' }
  },
  {
    id: '78890398-2',
    score: 0.8999873298772428,
    document: { name: 'apple is a' }
  },
  {
    id: '78890398-3',
    score: 0.8999873298772428,
    document: { name: 'to serve as a' }
  },
  {
    id: '78890398-4',
    score: 0.6722796921974584,
    document: { name: 'effort. apple is a' }
  },
  {
    id: '78890398-7',
    score: 0.6722796921974584,
    document: { name: 'you can always assert that it is incorrect' }
  },
  {
    id: '78890398-6',
    score: 0.5365309081960485,
    document: { name: 'of poisonous spike-pits, nay, a' }
  }
]
```

As you can see in the output, while the first hit is good, we are missing the hit for "assert" which occurs as the second last search result. I was expecting to see the result with "assert" to be first, and then I was expecting to see the result with "assertions" next. I'm also a little confused as to why we are seeing results with stop words occur at the top 5, especially since we are removing them via `stopWords: englishStopwords`

Please let me know if I missed anything here, or if I am doing something incorrectly. I am currently using version `2.0.8`

**Comment by rishabmahesh** [comment]
The above becomes significantly better after adding "a" to `englishStopwords`. Its odd that "a" isn't already in this list

**Comment by micheleriva** [comment]
@rishabmahesh would you mind opening a PR for this? 🙏

**Comment by rishabmahesh** [comment]
After cloning the repo to my computer, I followed the instructions stated in `CONTRIBUTING.md`. However, when I try to run `pnpm build`, I am getting the following error. Did I miss a step, or did I do something wrong? This is my first time contributing, so I would really appreciate your patience and guidance!

![image](https://github.com/askorama/orama/assets/40491438/cabfa5d0-a658-44cb-ae0e-888d68db5862)
