### ISSUE TITLE
threshold 0 does not match all properties

### ISSUE THREAD

**Issue by dpmillerau** [oramasearch/orama#924]
### Describe the bug

when I search with 2 words in the term  using threshold 0 all properties are not matched as per the threshold documentation #https://docs.orama.com/open-source/usage/search/threshold Instead no documents are returned when keywords should each match a property

> In this case, the threshold property is set to 0, which means that only the document containing the "slim fit" keywords will be returned. This applies to all the document properties; if a keyword is found in a property, and another keyword is found in a different property, the document will be returned.

### To Reproduce

```import { create, search, insert } from "@orama/orama";

const db = create({
  schema: {
    name: "string",
    description: "string",
  },
});

insert(
  db,
  {
    name: "brilliant wireless",
    description:
      "immersive",
  })
insert(
  db,
  {
    name: "brilliant bluetooth",
    description:
      "wonderful",
  }
)
insert(
  db,
  {
    name: "bluetooth Headphones",
    description:
      "wonderful",
  }
);
let searchResult = search(db, {
  term: "brilliant",
  threshold: 0,
});

console.log("brilliant")
console.log(searchResult.hits.map((hit) => hit.document));

searchResult = search(db, {
  term: "wonderful",
  threshold: 0,
});

console.log("wonderful")
console.log(searchResult.hits.map((hit) => hit.document));

searchResult = search(db, {
  term: "brilliant wonderful",
  threshold: 0
});

console.log("brilliant wonderful")
console.log(searchResult.hits.map((hit) => hit.document));
```

in 3.1.6 this returns

```
S C:\VsCode\orama> node .\index.js
(node:42032) [MODULE_TYPELESS_PACKAGE_JSON] Warning: Module type of file:///C:/VsCode/orama/index.js is not specified and it doesn't parse as CommonJS.
Reparsing as ES module because module syntax was detected. This incurs a performance overhead.
To eliminate this warning, add "type": "module" to C:\VsCode\orama\package.json.
(Use `node --trace-warnings ...` to show where the warning was created)
brilliant
[
  { name: 'brilliant wireless', description: 'immersive' },
  { name: 'brilliant bluetooth', description: 'wonderful' }
]
wonderful
[
  { name: 'brilliant bluetooth', description: 'wonderful' },
  { name: 'bluetooth Headphones', description: 'wonderful' }
]
brilliant wonderful
[]
```

### Expected behavior

searching term "brilliant wonderful"  should return 
[{ name: 'brilliant bluetooth', description: 'wonderful' }]

### Environment Info

```bash
OS: Windows 11 24H2
Node: 22.13.1
@orama/orama: 3.1.6
```

### Affected areas

Search

**Comment by micheleriva** [comment]
This should be fixed with #923, could you confirm please?

**Comment by Timbological** [comment]
@micheleriva 
This is actually still an issue in 3.1.13:

~/orama_test$ node repro.js
brilliant
[
  { name: 'brilliant wireless', description: 'immersive' },
  { name: 'brilliant bluetooth', description: 'wonderful' }
]
wonderful
[
  { name: 'brilliant bluetooth', description: 'wonderful' },
  { name: 'bluetooth Headphones', description: 'wonderful' }
]
brilliant wonderful
[]

Issue is here:
https://github.com/oramasearch/orama/blob/f837551471e316674957af8fa512e7a61fddabb7/packages/orama/src/components/index.ts#L563-571 

fullMatches is only the results where the number of matches in a particular property is the same as the number of search terms ie. one property contains all search terms, not where every search term is found across any properties (which is also what the comments say).

As the propertyMatches currently only shows how many terms each property matches and not which terms each property matches I think the calculateResultScores function would have to be updated to return this information

**Comment by Cyberheroes1010** [comment]
Biggest fruad Company !! Block me without paying my money !! Doing scam with researcher today i make a post on twitter & all social media !!

<img width="1701" height="835" alt="Image" src="https://github.com/user-attachments/assets/a9d5470d-00e0-4919-b64f-eebf35b2933e" />

<img width="1903" height="945" alt="Image" src="https://github.com/user-attachments/assets/e2f28ac4-967f-4f85-96db-da3a3d784413" />
<img width="1601" height="823" alt="Image" src="https://github.com/user-attachments/assets/071d318a-565d-4357-8257-7613b1d83c81" />
